In [43]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
%matplotlib inline

In [57]:

with open('university_towns.txt','r') as f:
    State_RegionName = []
    for line in f:
        if '[edit]' in line:
            state = line[:-7]
            continue
        if '(' in line:
            town = line.split('(',1)[0]
            State_RegionName.append([state,town])
        else:
            town=line
            State_RegionName.append([state,town])
state_town_df = pd.DataFrame(State_RegionName,columns=['State','RegionName'])
state_town_df

             State                     RegionName
0          Alabama                        Auburn
1          Alabama                      Florence
2          Alabama                  Jacksonville
3          Alabama                    Livingston
4          Alabama                    Montevallo
5          Alabama                          Troy
6          Alabama                    Tuscaloosa
7          Alabama                      Tuskegee
8           Alaska                     Fairbanks
9          Arizona                     Flagstaff
10         Arizona                         Tempe
11         Arizona                        Tucson
12        Arkansas                   Arkadelphia
13        Arkansas                        Conway
14        Arkansas                  Fayetteville
15        Arkansas                     Jonesboro
16        Arkansas                      Magnolia
17        Arkansas                    Monticello
18        Arkansas                  Russellville
19        Arkansas                        Searcy
20      California                        Angwin
21      California                        Arcata
22      California                      Berkeley
23      California                         Chico
24      California                     Claremont
25      California                        Cotati
26      California                         Davis
27      California                        Irvine
28      California                    Isla Vista
29      California  University Park, Los Angeles
..             ...                            ...
487       Virginia                          Wise
488       Virginia                    Chesapeake
489     Washington                    Bellingham
490     Washington                        Cheney
491     Washington                    Ellensburg
492     Washington                       Pullman
493     Washington  University District, Seattle
494  West Virginia                        Athens
495  West Virginia                    Buckhannon
496  West Virginia                      Fairmont
497  West Virginia                     Glenville
498  West Virginia                    Huntington
499  West Virginia                    Montgomery
500  West Virginia                    Morgantown
501  West Virginia                 Shepherdstown
502  West Virginia                  West Liberty
503      Wisconsin                      Appleton
504      Wisconsin                    Eau Claire
505      Wisconsin                     Green Bay
506      Wisconsin                     La Crosse
507      Wisconsin                       Madison
508      Wisconsin                     Menomonie
509      Wisconsin                     Milwaukee
510      Wisconsin                       Oshkosh
511      Wisconsin                   Platteville
512      Wisconsin                   River Falls
513      Wisconsin                 Stevens Point
514      Wisconsin                      Waukesha
515      Wisconsin                    Whitewater
516        Wyoming                       Laramie

[517 rows x 2 columns]

In [250]:
states = {'OH': 'Ohio', 'KY': 'Kentucky', 'AS': 'American Samoa', 'NV': 'Nevada', 'WY': 'Wyoming', 'NA': 'National', 'AL': 'Alabama', 'MD': 'Maryland', 'AK': 'Alaska', 'UT': 'Utah', 'OR': 'Oregon', 'MT': 'Montana', 'IL': 'Illinois', 'TN': 'Tennessee', 'DC': 'District of Columbia', 'VT': 'Vermont', 'ID': 'Idaho', 'AR': 'Arkansas', 'ME': 'Maine', 'WA': 'Washington', 'HI': 'Hawaii', 'WI': 'Wisconsin', 'MI': 'Michigan', 'IN': 'Indiana', 'NJ': 'New Jersey', 'AZ': 'Arizona', 'GU': 'Guam', 'MS': 'Mississippi', 'PR': 'Puerto Rico', 'NC': 'North Carolina', 'TX': 'Texas', 'SD': 'South Dakota', 'MP': 'Northern Mariana Islands', 'IA': 'Iowa', 'MO': 'Missouri', 'CT': 'Connecticut', 'WV': 'West Virginia', 'SC': 'South Carolina', 'LA': 'Louisiana', 'KS': 'Kansas', 'NY': 'New York', 'NE': 'Nebraska', 'OK': 'Oklahoma', 'FL': 'Florida', 'CA': 'California', 'CO': 'Colorado', 'PA': 'Pennsylvania', 'DE': 'Delaware', 'NM': 'New Mexico', 'RI': 'Rhode Island', 'MN': 'Minnesota', 'VI': 'Virgin Islands', 'NH': 'New Hampshire', 'MA': 'Massachusetts', 'GA': 'Georgia', 'ND': 'North Dakota', 'VA': 'Virginia'}

In [251]:
data = pd.read_csv('City_Zhvi_AllHomes.csv')
data.head()

,RegionID,RegionName,State,Metro,CountyName,SizeRank,1996-04,1996-05,1996-06,1996-07,...,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10
0,6181,New York,NY,New York,Queens,1,NaN,NaN,NaN,NaN,...,627300,634200,643200,653600,666400,676600,682800,689200,694200,696300
1,12447,Los Angeles,CA,Los Angeles-Long Beach-Anaheim,Los Angeles,2,155000.0,154600.0,154400.0,154200.0,...,611400,615400,620300,624200,627100,628900,630200,631900,634100,635500
2,17426,Chicago,IL,Chicago,Cook,3,109700.0,109400.0,109300.0,109300.0,...,216800,218700,219200,219600,220000,220100,220700,221700,221900,221600
3,13271,Philadelphia,PA,Philadelphia,Philadelphia,4,50000.0,49900.0,49600.0,49400.0,...,133800,134700,135300,135600,136300,136900,137500,138600,139700,140200
4,40326,Phoenix,AZ,Phoenix,Maricopa,5,87200.0,87700.0,88200.0,88400.0,...,206400,207600,208600,209400,211200,213600,215500,217000,218700,220200

In [253]:
data['State'].map(states)

0                    New York
1                  California
2                    Illinois
3                Pennsylvania
4                     Arizona
5                      Nevada
6                  California
7                       Texas
8                  California
9                     Florida
10                 California
11                      Texas
12                   Michigan
13                       Ohio
14                  Tennessee
15             North Carolina
16                      Texas
17              Massachusetts
18                 Washington
19                   Maryland
20                   Colorado
21       District of Columbia
22                  Tennessee
23                  Wisconsin
24                    Arizona
25                     Oregon
26                   Oklahoma
27                   Nebraska
28                 New Mexico
29                 California
                 ...
13069                Missouri
13070               Wisconsin
13071                Michigan
13072                Arkansas
13073               Wisconsin
13074                New York
13075                Nebraska
13076                  Hawaii
13077          South Carolina
13078                Michigan
13079                Arkansas
13080                 Indiana
13081               Tennessee
13082                Maryland
13083                 Indiana
13084              California
13085                Michigan
13086               Minnesota
13087                Missouri
13088                Virginia
13089              New Jersey
13090               Wisconsin
13091            Pennsylvania
13092            Pennsylvania
13093               Wisconsin
13094                New York
13095               Wisconsin
13096              California
13097               Wisconsin
13098              New Jersey
Name: State, Length: 13099, dtype: object

In [246]:
def get_recession():
    gdplev = pd.ExcelFile('gdplev.xls').parse(skiprows=5)
    gdplev = gdplev[['Unnamed: 4','GDP in billions of current dollars.1']]
    gdplev.columns=['YearQ','GDP']
    
    two_thousand = gdplev.loc[gdplev['YearQ']=='2000q1'].index[0]
    gdplev = gdplev.loc[two_thousand:]
    gdplev.reset_index(inplace=True,drop=True)
    for i in range(1,3):
        gdplev['GDP'+str(i)]=list(gdplev['GDP'][i:])+[np.nan]*i
    gdplev['start_q'] = (gdplev['GDP2']<gdplev['GDP1'])&(gdplev['GDP2']<gdplev['GDP'])
    first_q = gdplev['YearQ'][gdplev['start_q']==True]
    return gdplev
df = get_recession()

In [249]:
df

     YearQ      GDP     GDP1     GDP2  start_q
0   2000q1  10031.0  10278.3  10357.4    False
1   2000q2  10278.3  10357.4  10472.3    False
2   2000q3  10357.4  10472.3  10508.1    False
3   2000q4  10472.3  10508.1  10638.4    False
4   2001q1  10508.1  10638.4  10639.5    False
5   2001q2  10638.4  10639.5  10701.3    False
6   2001q3  10639.5  10701.3  10834.4    False
7   2001q4  10701.3  10834.4  10934.8    False
8   2002q1  10834.4  10934.8  11037.1    False
9   2002q2  10934.8  11037.1  11103.8    False
10  2002q3  11037.1  11103.8  11230.1    False
11  2002q4  11103.8  11230.1  11370.7    False
12  2003q1  11230.1  11370.7  11625.1    False
13  2003q2  11370.7  11625.1  11816.8    False
14  2003q3  11625.1  11816.8  11988.4    False
15  2003q4  11816.8  11988.4  12181.4    False
16  2004q1  11988.4  12181.4  12367.7    False
17  2004q2  12181.4  12367.7  12562.2    False
18  2004q3  12367.7  12562.2  12813.7    False
19  2004q4  12562.2  12813.7  12974.1    False
20  2005q1  12813.7  12974.1  13205.4    False
21  2005q2  12974.1  13205.4  13381.6    False
22  2005q3  13205.4  13381.6  13648.9    False
23  2005q4  13381.6  13648.9  13799.8    False
24  2006q1  13648.9  13799.8  13908.5    False
25  2006q2  13799.8  13908.5  14066.4    False
26  2006q3  13908.5  14066.4  14233.2    False
27  2006q4  14066.4  14233.2  14422.3    False
28  2007q1  14233.2  14422.3  14569.7    False
29  2007q2  14422.3  14569.7  14685.3    False
..     ...      ...      ...      ...      ...
36  2009q1  14383.9  14340.4  14384.1    False
37  2009q2  14340.4  14384.1  14566.5    False
38  2009q3  14384.1  14566.5  14681.1    False
39  2009q4  14566.5  14681.1  14888.6    False
40  2010q1  14681.1  14888.6  15057.7    False
41  2010q2  14888.6  15057.7  15230.2    False
42  2010q3  15057.7  15230.2  15238.4    False
43  2010q4  15230.2  15238.4  15460.9    False
44  2011q1  15238.4  15460.9  15587.1    False
45  2011q2  15460.9  15587.1  15785.3    False
46  2011q3  15587.1  15785.3  15973.9    False
47  2011q4  15785.3  15973.9  16121.9    False
48  2012q1  15973.9  16121.9  16227.9    False
49  2012q2  16121.9  16227.9  16297.3    False
50  2012q3  16227.9  16297.3  16475.4    False
51  2012q4  16297.3  16475.4  16541.4    False
52  2013q1  16475.4  16541.4  16749.3    False
53  2013q2  16541.4  16749.3  16999.9    False
54  2013q3  16749.3  16999.9  17025.2    False
55  2013q4  16999.9  17025.2  17285.6    False
56  2014q1  17025.2  17285.6  17569.4    False
57  2014q2  17285.6  17569.4  17692.2    False
58  2014q3  17569.4  17692.2  17783.6    False
59  2014q4  17692.2  17783.6  17998.3    False
60  2015q1  17783.6  17998.3  18141.9    False
61  2015q2  17998.3  18141.9  18222.8    False
62  2015q3  18141.9  18222.8  18281.6    False
63  2015q4  18222.8  18281.6  18450.1    False
64  2016q1  18281.6  18450.1      NaN    False
65  2016q2  18450.1      NaN      NaN    False

[66 rows x 5 columns]

In [146]:
[np.nan]*2

[nan, nan]

In [129]:

def get_recession_start():
    '''Returns the year and quarter of the recession start time as a 
    string value in a format such as 2005q3'''
    gdplev = pd.ExcelFile('gdplev.xls')
    gdplev = gdplev.parse("Sheet1", skiprows=219)
    gdplev = gdplev[['1999q4', 9926.1]]
    gdplev.columns = ['Quarter','GDP']
    
    for i in range(1,5):
        gdplev['GDP'+str(i)]=np.nan
    return gdplev

    

get_recession_start().loc[0]

Quarter    2000q1
GDP         10031
GDP1          NaN
GDP2          NaN
GDP3          NaN
GDP4          NaN
Name: 0, dtype: object

In [243]:

def get_recession_end():
    '''Returns the year and quarter of the recession end time as a 
    string value in a format such as 2005q3'''
    gdplev = pd.ExcelFile('gdplev.xls')
    gdplev = gdplev.parse("Sheet1", skiprows=219)
    gdplev = gdplev[['1999q4', 9926.1]]
    gdplev.columns = ['Quarter','GDP']
    start = get_recession_start()
    start_index = gdplev[gdplev['Quarter'] == start].index.tolist()[0]
    gdplev=gdplev.iloc[start_index:]
    for i in range(2, len(gdplev)):
        if (gdplev.iloc[i-2][1] < gdplev.iloc[i-1][1]) and (gdplev.iloc[i-1][1] < gdplev.iloc[i][1]):
            return gdplev.iloc[i][0]

In [244]:
get_recession_end()

/Users/spydermac/anaconda/lib/python3.6/site-packages/pandas/core/indexes/base.py:2984: RuntimeWarning: '<' not supported between instances of 'str' and 'int', sort order is undefined for incomparable objects
  return this.join(other, how=how, return_indexers=return_indexers)

'2000q3'

In [339]:
def convert_housing():
    zillow_data = pd.read_csv('City_Zhvi_AllHomes.csv')
    zillow_data['State']=zillow_data['State'].map(states)
    zillow_data.drop(['RegionID','Metro','CountyName','SizeRank'], inplace = True,axis=1)
    zillow_data.set_index(['State','RegionName'],inplace=True)
    zillow_data.columns=pd.to_datetime(zillow_data.columns)
    zillow_data=zillow_data.resample('Q',axis=1).mean()
    zillow_data.columns= pd.PeriodIndex(zillow_data.columns,freq='Q',inplace=True)
    zillow_data=zillow_data.loc[:,'2000q1':'2016q3']
    return zillow_data

In [358]:
% timeit -n 5 convert_housing()

5 loops, best of 3: 586 ms per loop

In [333]:
data.loc[:,'1997Q1':]

                                                 1997Q1         1997Q2  \
State                RegionName
New York             New York                       NaN            NaN
California           Los Angeles          156866.666667  158533.333333
Illinois             Chicago              111266.666667  112200.000000
Pennsylvania         Philadelphia          49600.000000   49733.333333
Arizona              Phoenix               91266.666667   92033.333333
Nevada               Las Vegas            122633.333333  123666.666667
California           San Diego            160633.333333  161966.666667
Texas                Dallas                68450.000000   67200.000000
California           San Jose             239300.000000  246166.666667
Florida              Jacksonville          76800.000000   77200.000000
California           San Francisco        276133.333333  284600.000000
Texas                Austin                         NaN  121600.000000
Michigan             Detroit               73733.333333   66000.000000
Ohio                 Columbus              84233.333333   84600.000000
Tennessee            Memphis               62333.333333   63166.666667
North Carolina       Charlotte            103400.000000  106933.333333
Texas                El Paso               70266.666667   70766.666667
Massachusetts        Boston               132000.000000  136566.666667
Washington           Seattle              168500.000000  172166.666667
Maryland             Baltimore             55333.333333   55100.000000
Colorado             Denver               108766.666667  115333.333333
District of Columbia Washington                     NaN            NaN
Tennessee            Nashville             89200.000000   90800.000000
Wisconsin            Milwaukee             68500.000000   68966.666667
Arizona              Tucson                92066.666667   92533.333333
Oregon               Portland             129500.000000  131533.333333
Oklahoma             Oklahoma City         66200.000000   66800.000000
Nebraska             Omaha                 92133.333333   93733.333333
New Mexico           Albuquerque          118400.000000  119533.333333
California           Fresno                89033.333333   88966.666667
...                                                 ...            ...
Missouri             Garden City          122500.000000  122500.000000
Wisconsin            Hager City           124500.000000  121366.666667
Michigan             Lake Isabella                  NaN            NaN
Arkansas             Mountainburg          55300.000000   53933.333333
Wisconsin            Oostburg              88300.000000   90733.333333
New York             Upper Brookville     900000.000000  905233.333333
Nebraska             Utica                 75950.000000   77633.333333
Hawaii               Volcano               96633.333333  104433.333333
South Carolina       Wedgefield                     NaN            NaN
Michigan             Williamston          135300.000000  135300.000000
Arkansas             Decatur               56566.666667   58900.000000
Indiana              Edgewood              84350.000000   83533.333333
Tennessee            Palmyra                        NaN            NaN
Maryland             Saint Inigoes        133000.000000  133466.666667
Indiana              Marysville                     NaN            NaN
California           Forest Falls          79733.333333   83366.666667
Michigan             Greilickville                  NaN            NaN
Minnesota            McGrath                        NaN            NaN
Missouri             Bois D Arc            81233.333333   85200.000000
Virginia             Henrico              112000.000000  113066.666667
New Jersey           Diamond Beach        141700.000000  147966.666667
Wisconsin            Lake Ripley          124533.333333  125100.000000
Pennsylvania         Highland Township    117566.666667  119100.000000
                     Palmyra Township      90833.333333   93700.000000
Wisconsin            Town of Wrightstown            NaN            NaN
New York             Urbana                66466.666667   68166.666667
Wisconsin            New Denmark                    NaN            NaN
California           Angels               112833.333333  116500.000000
Wisconsin            Holland              127566.666667  126500.000000
New Jersey           Lebanon Borough      144533.333333  147666.666667

                                                 1997Q3         1997Q4  \
State                RegionName
New York             New York                       NaN            NaN
California           Los Angeles          159266.666667  162000.000000
Illinois             Chicago              112966.666667  114833.333333
Pennsylvania         Philadelphia          49733.333333   49866.666667
Arizona              Phoenix               93000.000000   94633.333333
Nevada               Las Vegas            123700.000000  124600.000000
California           San Diego            163333.333333  168200.000000
Texas                Dallas                67200.000000   70300.000000
California           San Jose             255500.000000  266066.666667
Florida              Jacksonville          77766.666667   78900.000000
California           San Francisco        293700.000000  303033.333333
Texas                Austin               122933.333333  124933.333333
Michigan             Detroit               64433.333333   64500.000000
Ohio                 Columbus              85500.000000   86633.333333
Tennessee            Memphis               63766.666667   64600.000000
North Carolina       Charlotte            108900.000000  110633.333333
Texas                El Paso               71733.333333   72733.333333
Massachusetts        Boston               140233.333333  144333.333333
Washington           Seattle              177333.333333  183333.333333
Maryland             Baltimore             54800.000000   54933.333333
Colorado             Denver               121066.666667  125200.000000
District of Columbia Washington                     NaN            NaN
Tennessee            Nashville             91800.000000   93900.000000
Wisconsin            Milwaukee             69733.333333   71000.000000
Arizona              Tucson                92833.333333   93600.000000
Oregon               Portland             133866.666667  136966.666667
Oklahoma             Oklahoma City         67233.333333   67833.333333
Nebraska             Omaha                 95233.333333   97100.000000
New Mexico           Albuquerque          120400.000000  120900.000000
California           Fresno                88766.666667   88466.666667
...                                                 ...            ...
Missouri             Garden City          122400.000000  122400.000000
Wisconsin            Hager City           118866.666667  123800.000000
Michigan             Lake Isabella                  NaN            NaN
Arkansas             Mountainburg          56366.666667   55933.333333
Wisconsin            Oostburg              92866.666667   95800.000000
New York             Upper Brookville     902800.000000  911066.666667
Nebraska             Utica                 79300.000000   80033.333333
Hawaii               Volcano              103000.000000   99200.000000
South Carolina       Wedgefield                     NaN            NaN
Michigan             Williamston          133800.000000  136433.333333
Arkansas             Decatur               60833.333333   62466.666667
Indiana              Edgewood              83433.333333   83033.333333
Tennessee            Palmyra                        NaN            NaN
Maryland             Saint Inigoes        136366.666667  139433.333333
Indiana              Marysville                     NaN            NaN
California           Forest Falls          89066.666667   90133.333333
Michigan             Greilickville                  NaN            NaN
Minnesota            McGrath                        NaN            NaN
Missouri             Bois D Arc            89533.333333   90333.333333
Virginia             Henrico              114100.000000  115400.000000
New Jersey           Diamond Beach        152833.333333  153133.333333
Wisconsin            Lake Ripley          124200.000000  122533.333333
Pennsylvania         Highland Township    120266.666667  122466.666667
                     Palmyra Township      92433.333333   90766.666667
Wisconsin            Town of Wrightstown            NaN            NaN
New York             Urbana                72066.666667   73766.666667
Wisconsin            New Denmark                    NaN            NaN
California           Angels               115966.666667  121466.666667
Wisconsin            Holland              129266.666667  135866.666667
New Jersey           Lebanon Borough      149533.333333  148966.666667

                                                 1998Q1         1998Q2  \
State                RegionName
New York             New York                       NaN            NaN
California           Los Angeles          166966.666667  171400.000000
Illinois             Chicago              116966.666667  118433.333333
Pennsylvania         Philadelphia          50300.000000   50800.000000
Arizona              Phoenix               96733.333333   98433.333333
Nevada               Las Vegas            125166.666667  125700.000000
California           San Diego            174633.333333  180333.333333
Texas                Dallas                73200.000000   72166.666667
California           San Jose             275500.000000  282966.666667
Florida              Jacksonville          80000.000000   80566.666667
California           San Francisco        315433.333333  326166.666667
Texas                Austin               128033.333333  129066.666667
Michigan             Detroit               64600.000000   62666.666667
Ohio                 Columbus              87500.000000   88266.666667
Tennessee            Memphis               65566.666667   66366.666667
North Carolina       Charlotte            112900.000000  114666.666667
Texas                El Paso               73133.333333   72933.333333
Massachusetts        Boston               149366.666667  154866.666667
Washington           Seattle              190966.666667  199433.333333
Maryland             Baltimore             55700.000000   56133.333333
Colorado             Denver               126800.000000  127933.333333
District of Columbia Washington                     NaN            NaN
Tennessee            Nashville             97300.000000  101000.000000
Wisconsin            Milwaukee             72100.000000   72633.333333
Arizona              Tucson                94466.666667   95300.000000
Oregon               Portland             139933.333333  142400.000000
Oklahoma             Oklahoma City         68933.333333   69666.666667
Nebraska             Omaha                 98666.666667   99233.333333
New Mexico           Albuquerque          121466.666667  122166.666667
California           Fresno                88700.000000   88600.000000
...                                                 ...            ...
Missouri             Garden City          122466.666667  122500.000000
Wisconsin            Hager City           124800.000000  125233.333333
Michigan             Lake Isabella                  NaN            NaN
Arkansas             Mountainburg          55900.000000   57866.666667
Wisconsin            Oostburg              96800.000000   98100.000000
New York             Upper Brookville     919200.000000  935866.666667
Nebraska             Utica                 82666.666667   83433.333333
Hawaii               Volcano               93500.000000   88600.000000
South Carolina       Wedgefield                     NaN            NaN
Michigan             Williamston          139500.000000  141000.000000
Arkansas             Decatur               63633.333333   63266.666667
Indiana              Edgewood              83633.333333   85166.666667
Tennessee            Palmyra                        NaN            NaN
Maryland             Saint Inigoes        144466.666667  146833.333333
Indiana              Marysville                     NaN            NaN
California           Forest Falls          91333.333333   93300.000000
Michigan             Greilickville                  NaN            NaN
Minnesota            McGrath                        NaN            NaN
Missouri             Bois D Arc            91066.666667   93266.666667
Virginia             Henrico              116733.333333  117266.666667
New Jersey           Diamond Beach        154066.666667  157033.333333
Wisconsin            Lake Ripley          119633.333333  118166.666667
Pennsylvania         Highland Township    126900.000000  129933.333333
                     Palmyra Township      90500.000000   89200.000000
Wisconsin            Town of Wrightstown  110550.000000  119866.666667
New York             Urbana                76366.666667   77866.666667
Wisconsin            New Denmark          127000.000000  135933.333333
California           Angels               129100.000000  131800.000000
Wisconsin            Holland              141233.333333  146166.666667
New Jersey           Lebanon Borough      149933.333333  151033.333333

                                                 1998Q3         1998Q4  \
State                RegionName
New York             New York                       NaN            NaN
California           Los Angeles          175966.666667  182366.666667
Illinois             Chicago              120700.000000  122633.333333
Pennsylvania         Philadelphia          50666.666667   50633.333333
Arizona              Phoenix              100433.333333  101733.333333
Nevada               Las Vegas            127166.666667  127766.666667
California           San Diego            183700.000000  188800.000000
Texas                Dallas                71833.333333   73966.666667
California           San Jose             292400.000000  300233.333333
Florida              Jacksonville          80966.666667   81100.000000
California           San Francisco        334600.000000  341200.000000
Texas                Austin               128966.666667  129266.666667
Michigan             Detroit               60833.333333   59000.000000
Ohio                 Columbus              88533.333333   88933.333333
Tennessee            Memphis               67266.666667   68200.000000
North Carolina       Charlotte            116833.333333  119900.000000
Texas                El Paso               72733.333333   72866.666667
Massachusetts        Boston               159100.000000  163600.000000
Washington           Seattle              208000.000000  214233.333333
Maryland             Baltimore             56500.000000   56700.000000
Colorado             Denver               130033.333333  133633.333333
District of Columbia Washington                     NaN            NaN
Tennessee            Nashville            104800.000000  108733.333333
Wisconsin            Milwaukee             72466.666667   72700.000000
Arizona              Tucson                95733.333333   96633.333333
Oregon               Portland             143900.000000  145566.666667
Oklahoma             Oklahoma City         70733.333333   72366.666667
Nebraska             Omaha                101133.333333  103766.666667
New Mexico           Albuquerque          122433.333333  122900.000000
California           Fresno                88166.666667   88233.333333
...                                                 ...            ...
Missouri             Garden City          122400.000000  122400.000000
Wisconsin            Hager City           125000.000000  123500.000000
Michigan             Lake Isabella                  NaN            NaN
Arkansas             Mountainburg          57200.000000   57533.333333
Wisconsin            Oostburg              99966.666667   98000.000000
New York             Upper Brookville     967966.666667  980633.333333
Nebraska             Utica                 82166.666667   80000.000000
Hawaii               Volcano               91633.333333   96900.000000
South Carolina       Wedgefield                     NaN            NaN
Michigan             Williamston          143266.666667  145233.333333
Arkansas             Decatur               63100.000000   61000.000000
Indiana              Edgewood              87566.666667   90366.666667
Tennessee            Palmyra                        NaN            NaN
Maryland             Saint Inigoes        147033.333333  151033.333333
Indiana              Marysville                     NaN            NaN
California           Forest Falls          97766.666667  102366.666667
Michigan             Greilickville                  NaN            NaN
Minnesota            McGrath                        NaN            NaN
Missouri             Bois D Arc            93300.000000   92933.333333
Virginia             Henrico              118133.333333  119366.666667
New Jersey           Diamond Beach        158066.666667  164033.333333
Wisconsin            Lake Ripley          120333.333333  125333.333333
Pennsylvania         Highland Township    130300.000000  134300.000000
                     Palmyra Township      84700.000000   85966.666667
Wisconsin            Town of Wrightstown  119966.666667  113166.666667
New York             Urbana                74400.000000   77933.333333
Wisconsin            New Denmark          137933.333333  128800.000000
California           Angels               133266.666667  132000.000000
Wisconsin            Holland              143133.333333  142700.000000
New Jersey           Lebanon Borough      150300.000000  153900.000000

                                                1999Q1        1999Q2  \
State                RegionName
New York             New York                      NaN           NaN
California           Los Angeles          1.869000e+05  1.913333e+05
Illinois             Chicago              1.238333e+05  1.272667e+05
Pennsylvania         Philadelphia         5.093333e+04  5.136667e+04
Arizona              Phoenix              1.039000e+05  1.057333e+05
Nevada               Las Vegas            1.277333e+05  1.283667e+05
California           San Diego            1.935667e+05  1.996000e+05
Texas                Dallas               7.733333e+04  7.943333e+04
California           San Jose             3.064000e+05  3.126667e+05
Florida              Jacksonville         8.243333e+04  8.440000e+04
California           San Francisco        3.463000e+05  3.512333e+05
Texas                Austin               1.313667e+05  1.337333e+05
Michigan             Detroit              5.816667e+04  5.950000e+04
Ohio                 Columbus             9.013333e+04  9.150000e+04
Tennessee            Memphis              6.966667e+04  7.016667e+04
North Carolina       Charlotte            1.205000e+05  1.227667e+05
Texas                El Paso              7.313333e+04  7.386667e+04
Massachusetts        Boston               1.694333e+05  1.787333e+05
Washington           Seattle              2.199333e+05  2.259667e+05
Maryland             Baltimore            5.703333e+04  5.773333e+04
Colorado             Denver               1.390667e+05  1.454667e+05
District of Columbia Washington                    NaN  1.274000e+05
Tennessee            Nashville            1.099333e+05  1.103000e+05
Wisconsin            Milwaukee            7.330000e+04  7.453333e+04
Arizona              Tucson               9.826667e+04  9.930000e+04
Oregon               Portland             1.474333e+05  1.489333e+05
Oklahoma             Oklahoma City        7.333333e+04  7.360000e+04
Nebraska             Omaha                1.063667e+05  1.096667e+05
New Mexico           Albuquerque          1.234333e+05  1.236667e+05
California           Fresno               8.903333e+04  9.016667e+04
...                                                ...           ...

In [279]:
pd.PeriodIndex(convert_housing().columns,freq='Q')

PeriodIndex(['1996Q2', '1996Q2', '1996Q2', '1996Q3', '1996Q3', '1996Q3',
             '1996Q4', '1996Q4', '1996Q4', '1997Q1',
             ...
             '2017Q1', '2017Q1', '2017Q1', '2017Q2', '2017Q2', '2017Q2',
             '2017Q3', '2017Q3', '2017Q3', '2017Q4'],
            dtype='period[Q-DEC]', length=259, freq='Q-DEC')

In [318]:
data.resample('Q',axis=1).mean()

                                             1996-06-30     1996-09-30  \
State                RegionName
New York             New York                       NaN            NaN
California           Los Angeles          154666.666667  154200.000000
Illinois             Chicago              109466.666667  109133.333333
Pennsylvania         Philadelphia          49833.333333   49366.666667
Arizona              Phoenix               87700.000000   88600.000000
Nevada               Las Vegas            120966.666667  120266.666667
California           San Diego            160733.333333  159600.000000
Texas                Dallas                         NaN            NaN
California           San Jose             224933.333333  227100.000000
Florida              Jacksonville          77166.666667   76300.000000
California           San Francisco        263366.666667  266200.000000
Texas                Austin                         NaN            NaN
Michigan             Detroit               81250.000000   80866.666667
Ohio                 Columbus              83200.000000   83600.000000
Tennessee            Memphis               60600.000000   61033.333333
North Carolina       Charlotte             95033.333333   97266.666667
Texas                El Paso               67733.333333   68400.000000
Massachusetts        Boston               123000.000000  124600.000000
Washington           Seattle              163966.666667  163633.333333
Maryland             Baltimore             53833.333333   54766.666667
Colorado             Denver                99166.666667  101100.000000
District of Columbia Washington                     NaN            NaN
Tennessee            Nashville             83900.000000   86466.666667
Wisconsin            Milwaukee             68100.000000   67700.000000
Arizona              Tucson                91533.333333   91566.666667
Oregon               Portland             122100.000000  124400.000000
Oklahoma             Oklahoma City         65333.333333   66000.000000
Nebraska             Omaha                 89633.333333   90966.666667
New Mexico           Albuquerque          115666.666667  116866.666667
California           Fresno                90333.333333   89800.000000
...                                                 ...            ...
Missouri             Garden City          122500.000000  122400.000000
Wisconsin            Hager City           115333.333333  118800.000000
Michigan             Lake Isabella                  NaN            NaN
Arkansas             Mountainburg          55500.000000   56633.333333
Wisconsin            Oostburg              85000.000000   84466.666667
New York             Upper Brookville     894166.666667  894900.000000
Nebraska             Utica                          NaN            NaN
Hawaii               Volcano              108533.333333   94066.666667
South Carolina       Wedgefield                     NaN            NaN
Michigan             Williamston          124633.333333  131366.666667
Arkansas             Decatur               54966.666667   54600.000000
Indiana              Edgewood                       NaN            NaN
Tennessee            Palmyra                        NaN            NaN
Maryland             Saint Inigoes        137266.666667  137700.000000
Indiana              Marysville                     NaN            NaN
California           Forest Falls          75366.666667   73300.000000
Michigan             Greilickville                  NaN            NaN
Minnesota            McGrath                        NaN            NaN
Missouri             Bois D Arc            77633.333333   79233.333333
Virginia             Henrico              110533.333333  111033.333333
New Jersey           Diamond Beach        136766.666667  133666.666667
Wisconsin            Lake Ripley          116300.000000  119133.333333
Pennsylvania         Highland Township    120200.000000  119000.000000
                     Palmyra Township     101366.666667  104633.333333
Wisconsin            Town of Wrightstown            NaN            NaN
New York             Urbana                66066.666667   65533.333333
Wisconsin            New Denmark                    NaN            NaN
California           Angels               116666.666667  118100.000000
Wisconsin            Holland              130133.333333  128333.333333
New Jersey           Lebanon Borough      142800.000000  140466.666667

                                             1996-12-31     1997-03-31  \
State                RegionName
New York             New York                       NaN            NaN
California           Los Angeles          154433.333333  156866.666667
Illinois             Chicago              109600.000000  111266.666667
Pennsylvania         Philadelphia          49466.666667   49600.000000
Arizona              Phoenix               89733.333333   91266.666667
Nevada               Las Vegas            120933.333333  122633.333333
California           San Diego            158633.333333  160633.333333
Texas                Dallas                         NaN   68450.000000
California           San Jose             231200.000000  239300.000000
Florida              Jacksonville          76033.333333   76800.000000
California           San Francisco        269266.666667  276133.333333
Texas                Austin                         NaN            NaN
Michigan             Detroit               80033.333333   73733.333333
Ohio                 Columbus              83900.000000   84233.333333
Tennessee            Memphis               61566.666667   62333.333333
North Carolina       Charlotte            100333.333333  103400.000000
Texas                El Paso               69500.000000   70266.666667
Massachusetts        Boston               127366.666667  132000.000000
Washington           Seattle              165200.000000  168500.000000
Maryland             Baltimore             54933.333333   55333.333333
Colorado             Denver               103566.666667  108766.666667
District of Columbia Washington                     NaN            NaN
Tennessee            Nashville             87800.000000   89200.000000
Wisconsin            Milwaukee             67900.000000   68500.000000
Arizona              Tucson                91700.000000   92066.666667
Oregon               Portland             126833.333333  129500.000000
Oklahoma             Oklahoma City         66066.666667   66200.000000
Nebraska             Omaha                 91266.666667   92133.333333
New Mexico           Albuquerque          117300.000000  118400.000000
California           Fresno                89066.666667   89033.333333
...                                                 ...            ...
Missouri             Garden City          122400.000000  122500.000000
Wisconsin            Hager City           120133.333333  124500.000000
Michigan             Lake Isabella                  NaN            NaN
Arkansas             Mountainburg          57433.333333   55300.000000
Wisconsin            Oostburg              86666.666667   88300.000000
New York             Upper Brookville     895200.000000  900000.000000
Nebraska             Utica                          NaN   75950.000000
Hawaii               Volcano               92300.000000   96633.333333
South Carolina       Wedgefield                     NaN            NaN
Michigan             Williamston          133033.333333  135300.000000
Arkansas             Decatur               55133.333333   56566.666667
Indiana              Edgewood                       NaN   84350.000000
Tennessee            Palmyra                        NaN            NaN
Maryland             Saint Inigoes        134800.000000  133000.000000
Indiana              Marysville                     NaN            NaN
California           Forest Falls          76900.000000   79733.333333
Michigan             Greilickville                  NaN            NaN
Minnesota            McGrath                        NaN            NaN
Missouri             Bois D Arc            78600.000000   81233.333333
Virginia             Henrico              111066.666667  112000.000000
New Jersey           Diamond Beach        134800.000000  141700.000000
Wisconsin            Lake Ripley          121166.666667  124533.333333
Pennsylvania         Highland Township    116833.333333  117566.666667
                     Palmyra Township      95400.000000   90833.333333
Wisconsin            Town of Wrightstown            NaN            NaN
New York             Urbana                64833.333333   66466.666667
Wisconsin            New Denmark                    NaN            NaN
California           Angels               114266.666667  112833.333333
Wisconsin            Holland              128900.000000  127566.666667
New Jersey           Lebanon Borough      141700.000000  144533.333333

                                             1997-06-30     1997-09-30  \
State                RegionName
New York             New York                       NaN            NaN
California           Los Angeles          158533.333333  159266.666667
Illinois             Chicago              112200.000000  112966.666667
Pennsylvania         Philadelphia          49733.333333   49733.333333
Arizona              Phoenix               92033.333333   93000.000000
Nevada               Las Vegas            123666.666667  123700.000000
California           San Diego            161966.666667  163333.333333
Texas                Dallas                67200.000000   67200.000000
California           San Jose             246166.666667  255500.000000
Florida              Jacksonville          77200.000000   77766.666667
California           San Francisco        284600.000000  293700.000000
Texas                Austin               121600.000000  122933.333333
Michigan             Detroit               66000.000000   64433.333333
Ohio                 Columbus              84600.000000   85500.000000
Tennessee            Memphis               63166.666667   63766.666667
North Carolina       Charlotte            106933.333333  108900.000000
Texas                El Paso               70766.666667   71733.333333
Massachusetts        Boston               136566.666667  140233.333333
Washington           Seattle              172166.666667  177333.333333
Maryland             Baltimore             55100.000000   54800.000000
Colorado             Denver               115333.333333  121066.666667
District of Columbia Washington                     NaN            NaN
Tennessee            Nashville             90800.000000   91800.000000
Wisconsin            Milwaukee             68966.666667   69733.333333
Arizona              Tucson                92533.333333   92833.333333
Oregon               Portland             131533.333333  133866.666667
Oklahoma             Oklahoma City         66800.000000   67233.333333
Nebraska             Omaha                 93733.333333   95233.333333
New Mexico           Albuquerque          119533.333333  120400.000000
California           Fresno                88966.666667   88766.666667
...                                                 ...            ...
Missouri             Garden City          122500.000000  122400.000000
Wisconsin            Hager City           121366.666667  118866.666667
Michigan             Lake Isabella                  NaN            NaN
Arkansas             Mountainburg          53933.333333   56366.666667
Wisconsin            Oostburg              90733.333333   92866.666667
New York             Upper Brookville     905233.333333  902800.000000
Nebraska             Utica                 77633.333333   79300.000000
Hawaii               Volcano              104433.333333  103000.000000
South Carolina       Wedgefield                     NaN            NaN
Michigan             Williamston          135300.000000  133800.000000
Arkansas             Decatur               58900.000000   60833.333333
Indiana              Edgewood              83533.333333   83433.333333
Tennessee            Palmyra                        NaN            NaN
Maryland             Saint Inigoes        133466.666667  136366.666667
Indiana              Marysville                     NaN            NaN
California           Forest Falls          83366.666667   89066.666667
Michigan             Greilickville                  NaN            NaN
Minnesota            McGrath                        NaN            NaN
Missouri             Bois D Arc            85200.000000   89533.333333
Virginia             Henrico              113066.666667  114100.000000
New Jersey           Diamond Beach        147966.666667  152833.333333
Wisconsin            Lake Ripley          125100.000000  124200.000000
Pennsylvania         Highland Township    119100.000000  120266.666667
                     Palmyra Township      93700.000000   92433.333333
Wisconsin            Town of Wrightstown            NaN            NaN
New York             Urbana                68166.666667   72066.666667
Wisconsin            New Denmark                    NaN            NaN
California           Angels               116500.000000  115966.666667
Wisconsin            Holland              126500.000000  129266.666667
New Jersey           Lebanon Borough      147666.666667  149533.333333

                                             1997-12-31     1998-03-31  \
State                RegionName
New York             New York                       NaN            NaN
California           Los Angeles          162000.000000  166966.666667
Illinois             Chicago              114833.333333  116966.666667
Pennsylvania         Philadelphia          49866.666667   50300.000000
Arizona              Phoenix               94633.333333   96733.333333
Nevada               Las Vegas            124600.000000  125166.666667
California           San Diego            168200.000000  174633.333333
Texas                Dallas                70300.000000   73200.000000
California           San Jose             266066.666667  275500.000000
Florida              Jacksonville          78900.000000   80000.000000
California           San Francisco        303033.333333  315433.333333
Texas                Austin               124933.333333  128033.333333
Michigan             Detroit               64500.000000   64600.000000
Ohio                 Columbus              86633.333333   87500.000000
Tennessee            Memphis               64600.000000   65566.666667
North Carolina       Charlotte            110633.333333  112900.000000
Texas                El Paso               72733.333333   73133.333333
Massachusetts        Boston               144333.333333  149366.666667
Washington           Seattle              183333.333333  190966.666667
Maryland             Baltimore             54933.333333   55700.000000
Colorado             Denver               125200.000000  126800.000000
District of Columbia Washington                     NaN            NaN
Tennessee            Nashville             93900.000000   97300.000000
Wisconsin            Milwaukee             71000.000000   72100.000000
Arizona              Tucson                93600.000000   94466.666667
Oregon               Portland             136966.666667  139933.333333
Oklahoma             Oklahoma City         67833.333333   68933.333333
Nebraska             Omaha                 97100.000000   98666.666667
New Mexico           Albuquerque          120900.000000  121466.666667
California           Fresno                88466.666667   88700.000000
...                                                 ...            ...
Missouri             Garden City          122400.000000  122466.666667
Wisconsin            Hager City           123800.000000  124800.000000
Michigan             Lake Isabella                  NaN            NaN
Arkansas             Mountainburg          55933.333333   55900.000000
Wisconsin            Oostburg              95800.000000   96800.000000
New York             Upper Brookville     911066.666667  919200.000000
Nebraska             Utica                 80033.333333   82666.666667
Hawaii               Volcano               99200.000000   93500.000000
South Carolina       Wedgefield                     NaN            NaN
Michigan             Williamston          136433.333333  139500.000000
Arkansas             Decatur               62466.666667   63633.333333
Indiana              Edgewood              83033.333333   83633.333333
Tennessee            Palmyra                        NaN            NaN
Maryland             Saint Inigoes        139433.333333  144466.666667
Indiana              Marysville                     NaN            NaN
California           Forest Falls          90133.333333   91333.333333
Michigan             Greilickville                  NaN            NaN
Minnesota            McGrath                        NaN            NaN
Missouri             Bois D Arc            90333.333333   91066.666667
Virginia             Henrico              115400.000000  116733.333333
New Jersey           Diamond Beach        153133.333333  154066.666667
Wisconsin            Lake Ripley          122533.333333  119633.333333
Pennsylvania         Highland Township    122466.666667  126900.000000
                     Palmyra Township      90766.666667   90500.000000
Wisconsin            Town of Wrightstown            NaN  110550.000000
New York             Urbana                73766.666667   76366.666667
Wisconsin            New Denmark                    NaN  127000.000000
California           Angels               121466.666667  129100.000000
Wisconsin            Holland              135866.666667  141233.333333
New Jersey           Lebanon Borough      148966.666667  149933.333333

                                             1998-06-30     1998-09-30  \
State                RegionName
New York             New York                       NaN            NaN
California           Los Angeles          171400.000000  175966.666667
Illinois             Chicago              118433.333333  120700.000000
Pennsylvania         Philadelphia          50800.000000   50666.666667
Arizona              Phoenix               98433.333333  100433.333333
Nevada               Las Vegas            125700.000000  127166.666667
California           San Diego            180333.333333  183700.000000
Texas                Dallas                72166.666667   71833.333333
California           San Jose             282966.666667  292400.000000
Florida              Jacksonville          80566.666667   80966.666667
California           San Francisco        326166.666667  334600.000000
Texas                Austin               129066.666667  128966.666667
Michigan             Detroit               62666.666667   60833.333333
Ohio                 Columbus              88266.666667   88533.333333
Tennessee            Memphis               66366.666667   67266.666667
North Carolina       Charlotte            114666.666667  116833.333333
Texas                El Paso               72933.333333   72733.333333
Massachusetts        Boston               154866.666667  159100.000000
Washington           Seattle              199433.333333  208000.000000
Maryland             Baltimore             56133.333333   56500.000000
Colorado             Denver               127933.333333  130033.333333
District of Columbia Washington                     NaN            NaN
Tennessee            Nashville            101000.000000  104800.000000
Wisconsin            Milwaukee             72633.333333   72466.666667
Arizona              Tucson                95300.000000   95733.333333
Oregon               Portland             142400.000000  143900.000000
Oklahoma             Oklahoma City         69666.666667   70733.333333
Nebraska             Omaha                 99233.333333  101133.333333
New Mexico           Albuquerque          122166.666667  122433.333333
California           Fresno                88600.000000   88166.666667

In [345]:
def new_col_names():
    #generating the new coloumns names 
    years = list(range(2000,2017))
    quars = ['q1','q2','q3','q4']
    quar_years = []
    for i in years:
        for x in quars:
            quar_years.append((str(i)+x))
    return quar_years[:67]
def convert_housing_data_to_quarters():
    '''Converts the housing data to quarters and returns it as mean 
    values in a dataframe. This dataframe should be a dataframe with
    columns for 2000q1 through 2016q3, and should have a multi-index
    in the shape of ["State","RegionName"].
    
    Note: Quarters are defined in the assignment description, they are
    not arbitrary three month periods.
    
    The resulting dataframe should have 67 columns, and 10,730 rows.
    '''
    data = pd.read_csv('City_Zhvi_AllHomes.csv')
    data.drop(['Metro','CountyName','RegionID','SizeRank'],axis=1,inplace=True)
    data['State'] = data['State'].map(states)
    data.set_index(['State','RegionName'],inplace=True)
    col = list(data.columns)
    col = col[0:45]
    data.drop(col,axis=1,inplace=True)

    #qs is the quarters of the year
    qs = [list(data.columns)[x:x+3] for x in range(0, len(list(data.columns)), 3)]
    
    # new columns
    column_names = new_col_names()
    for col,q in zip(column_names,qs):
        data[col] = data[q].mean(axis=1)
        
    data = data[column_names]
    return data

In [357]:
% timeit -n 5 convert_housing_data_to_quarters()

5 loops, best of 3: 1.78 s per loop